code-smell:
  active: true
  LongMethod:
    threshold: 20
  LongParameterList:
    threshold: 5
  LargeClass:
    threshold: 70
  ComplexMethod:
    threshold: 10

formatting:
  active: true
  autoCorrect: false
  Indentation:
    active: false
  ConsecutiveBlankLines:
    active: false

style:
  active: true
  WildcardImport:
  NoElseInWhenExpression:
  OptionalSemicolon:
  OptionalUnit:
  NamingConventionViolation:

comments:
  active: true
  CommentOverPrivateMethod:
    active: true
  CommentOverPrivateProperty:
    active: true
  NoDocOverPublicClass:
    active: false
  NoDocOverPublicMethod:
    active: false